clasificacion_futbol/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path

urlpatterns = [path('admin/', admin.site.urls),
               # CONTROL DE ACCESO USUARIO
               re_path(r'^', include(('users.urls', 'users'), namespace='users')),
               re_path(r'^', include(('clubes.urls', 'clubes'), namespace='clubes')),
               re_path(r'^', include(('core.urls', 'core'), namespace='core')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clubes/urls.py
# Users Urls

# Django
from django.urls import path, re_path

# importaciones de apps
from clubes import gestion_clubes

urlpatterns = [
    # CONTROL USUARIOS
    re_path(r'^gestion_clubes$', gestion_clubes.ViewSet.as_view(), name='gestion_clubes'),
]

core/urls.py
# Users Urls

# Django
from django.urls import path, re_path

# importaciones de apps
from core import api

urlpatterns = [
    # CONTROL USUARIOS
    re_path(r'^api', api.ViewSet.as_view(), name='api'),
]

clubes/models.py
from datetime import datetime

from django.db import models
from django.db.models import Sum, Value, Count
from django.db.models.functions import Coalesce

from core.models import ModeloBase
from users.models import Persona

TIPO_ROL = (
    (1, 'Jugador'),
    (2, 'Director Técnico'),
)
TIPO_JUGADOR = (
    (0, 'No es Jugador'),
    (1, 'Portero'),
    (2, 'Defensa'),
    (3, 'Centrocampista'),
    (4, 'Delantero'),
    (5, 'Suplente'),
    (6, 'Capitán'),
)

TIPO_CLUB = (
    (1, 'Hombres'),
    (2, 'Mujeres')
)
TIEMPOS = (
    (1, 'Primer Tiempo'),
    (2, 'Segundo Tiempo '),
    (3, 'Tiempo Extra Primer Tiempo'),
    (4, 'Tiempo Extra Primer Tiempo'),

)

ESTADO_PARTIDO = (
    (1, 'Planificado'),
    (2, 'Finalizado')
)
# Create your models here.
class Club(ModeloBase):
    nombre = models.CharField(default='', max_length=500, verbose_name=u"Nombre del club")
    descripcion = models.TextField(default='', verbose_name=u"descripción del club")
    tipoequipo = models.IntegerField(choices=TIPO_CLUB, default=1, verbose_name=u'Tipo de equipo')
    escudo = models.ImageField(upload_to='club', verbose_name=u'Escudo del club', blank=True, null=True)
    codigo = models.CharField(default='', blank=True, null=True, verbose_name='Codigo de consulta', max_length=500)
    
    def __str__(self):
        return u'%s' % self.nombre

    def generar_codigo(self):
        nombres = self.nombre.split(' ')
        siglas = ''
        for n in nombres:
            siglas += n[0].upper()
        numero = len(Club.objects.filter(status=True)) + 1
        palabra = f'{siglas}{self.id}{numero}'
        return palabra

    def generar_siglas(self):
        nombres = self.nombre.split(' ')
        siglas = ''
        for n in nombres:
            siglas += n[0].upper()
        palabra = f'{siglas}{self.id}'
        return palabra

    def club_in_torneo(self, idtorneo=None):
        if idtorneo:
            torneo = Torneo.objects.get(id=int(idtorneo))
            return self in torneo.equipos.all()
        return False

    def resultados_torneo(self, torneo):
        resultados = self.resultadopartido_set.filter(status=True, partido__torneo=torneo)
        tarjetas = self.tarjetapartido_set.filter(status=True, partido__torneo=torneo)
        pagorubros=self.pagorubrotarjeta_set.filter(status=True,torneo=torneo, estado=1)
        context = {'total_partidos': len(resultados),
                   'total_puntos': resultados.aggregate(totalpuntos=Coalesce(Sum('puntos'), Value(0)))['totalpuntos'],
                   'total_tarjetas': len(tarjetas),
                   'tarjeta': tarjetas.values('tipotarjeta__nombre').annotate(conteo=Count('id')),
                   'pendiente_pagar': tarjetas.filter(pagado=False).aggregate(totalpagar=Coalesce(Sum('valor'), Value(0.00)))['totalpagar'],
                   'total_pagado': tarjetas.filter(pagado=True).aggregate(totalpagar=Coalesce(Sum('valor'), Value(0.00)))['totalpagar'],
                   'total': tarjetas.aggregate(totalpagar=Coalesce(Sum('valor'), Value(0.00)))['totalpagar'],
                   'pagorubros': pagorubros
                   }
        return context

    def tarjetas_pagar(self, torneo):
        tarjetas = self.tarjetapartido_set.filter(status=True, partido__torneo=torneo, pagado=False)
        return {'tarjetas':tarjetas,'pendiente_pagar': tarjetas.aggregate(totalpagar=Coalesce(Sum('valor'), Value(0.00)))['totalpagar']}
    
    def total_integrantes(self):
        return self.integranteclub_set.filter(status=True)

    def siglas(self):
        nombre = self.nombre.split(' ')
        if len(nombre) == 1:
            siglas = self.nombre[0].upper() + self.nombre[-1].upper()
        else:
            siglas = nombre[0][0].upper() + nombre[1][0].upper()
        return siglas

    def get_escudo_html_40px(self):
        if self.escudo:
            return f'<div class="avatar avatar-md avatar-indicators avatar-online"><img alt="avatar" src="{self.escudo.url}"class="rounded-circle"/></div>'
        else:
            return f'<div class="siglas-md mt-0 ml-1"> <span class="mt-0 bg-secondary">{self.siglas()}</span></div>'

    def get_escudo_img_md(self):
        if self.escudo:
            return f'<img src="{self.escudo.url}" class="rounded-circle avatar-md me-2"/>'
        else:
            return f'<div class="siglas-md mt-0 ml-1 me-2"> <span class="mt-0 bg-secondary">{self.siglas()}</span></div>'

    def get_escudo_img_sm(self):
        if self.escudo:
            return f'<img src="{self.escudo.url}" class="rounded-circle avatar-xs me-2"/>'
        else:
            return f'<img src="/static/images/escudo.png" class="avatar-xs me-2"/>'

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = Club.objects.filter(nombre=self.nombre, status=True).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    def resultado_partido(self, partido):
        resultado = self.resultadopartido_set.filter(status=True, partido=partido).first()
        return resultado

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()
        super(Club, self).save(*args, **kwargs)

    class Meta:
        verbose_name = u"Club"
        verbose_name_plural = u"Clubes"
        ordering = ['nombre']


class IntegranteClub(ModeloBase):
    club = models.ForeignKey(Club, on_delete=models.CASCADE, verbose_name=u"Club")
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, verbose_name=u"Club")
    rol = models.IntegerField(choices=TIPO_ROL, default=1, verbose_name=u'Tipo de rol en el club')
    tipojugador = models.IntegerField(choices=TIPO_JUGADOR, default=0, verbose_name=u'Tipo de jugador en el club')
    suspendido = models.BooleanField(default=False, verbose_name=u'Integrante suspendido')
    
    def __str__(self):
        return f'{self.persona}'

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = IntegranteClub.objects.filter(status=True, club=self.club, persona=self.persona).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    class Meta:
        verbose_name = u"Integrante del club"
        verbose_name_plural = u"Integrantes del club"
        ordering = ['persona']


class Fase(ModeloBase):
    nombre = models.CharField(default='', max_length=500, verbose_name=u"Nombre de la fase")
    descripcion = models.TextField(default='', blank=True, null=True, verbose_name=u"descripción de la fase")

    def __str__(self):
        return f'{self.nombre}'

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = Fase.objects.filter(status=True, nombre=self.nombre).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    class Meta:
        verbose_name = u"Fase"
        verbose_name_plural = u"Fases"
        ordering = ['nombre']


class TipoPartido(ModeloBase):
    nombre = models.CharField(default='', max_length=500, verbose_name=u"Nombre del partido")
    descripcion = models.TextField(default='', blank=True, null=True, verbose_name=u"descripción del partido")

    def __str__(self):
        return f'{self.nombre}'

    def tipomarcado(self, torneo=False):
        if torneo:
            return torneo.tipopartidos.filter(id=self.id).exists()
        return torneo

    def fases(self):
        return self.tipopartidofase_set.filter(status=True)

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = TipoPartido.objects.filter(status=True, nombre=self.nombre).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    class Meta:
        verbose_name = u"Tipo Partido"
        verbose_name_plural = u"Tipos Partidos"
        ordering = ['nombre']


class TipoPartidoFase(ModeloBase):
    tipopartido = models.ForeignKey(TipoPartido, on_delete=models.CASCADE, verbose_name=u"Partido", )
    fase = models.ForeignKey(Fase, on_delete=models.CASCADE, verbose_name=u"Fase", )
    puntos = models.IntegerField(default=3, verbose_name=u"Puntos por partido")
    orden = models.IntegerField(default=0, verbose_name=u"Orden")

    def __str__(self):
        return f'{self.tipopartido}-{self.fase}'

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = TipoPartidoFase.objects.filter(status=True, tipopartido=self.tipopartido, fase=self.fase).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    class Meta:
        verbose_name = u"Fase de Partido"
        verbose_name_plural = u"Fases de Partidos"
        ordering = ['orden']


class Torneo(ModeloBase):
    nombre = models.CharField(default='', max_length=500, verbose_name=u"Nombre del torneo")
    tipopartidos = models.ManyToManyField(TipoPartido, verbose_name="Tipos de partidos que se jugaran")
    generotorneo = models.IntegerField(choices=TIPO_CLUB, default=1, verbose_name="genero de participantes")
    equipos = models.ManyToManyField(Club, verbose_name='Equipos que participan en el torneo')
    inicio = models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio del torneo')
    fin = models.DateTimeField(blank=True, null=True, verbose_name='Fecha que finaliza el torneo')
    
    def __str__(self):
        return f'{self.nombre}-{self.get_generotorneo_display()}'

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = Torneo.objects.filter(status=True, nombre=self.nombre).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

users/models/models_profile.py
import datetime
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q

from django.contrib.auth.models import User
from users.models.models_address import Pais, Provincia, Ciudad
from core.funciones import ruta_foto
from core.models import ModeloBase
from django.forms import model_to_dict

SEXO = (
    (1, u'Hombre'),
    (2, u'Mujer'),
)

PERFIL_USUARIO = (
    (0, 'Sin perfil'),
    (1, 'Administrador'),
    (2, 'Secretario'),
    (3, 'Asistente'),
    (4, 'Cliente'),
)

class Persona(ModeloBase):
    usuario = models.ForeignKey(User, null=True, blank=True,  on_delete=models.CASCADE)
    perfil = models.IntegerField(choices=PERFIL_USUARIO, default=0, verbose_name=u'Tipo de usuario')
    nombres = models.CharField(default='', max_length=100, verbose_name=u'Nombre')
    apellido1 = models.CharField(default='', max_length=50, verbose_name=u"1er Apellido")
    apellido2 = models.CharField(default='', max_length=50, verbose_name=u"2do Apellido")
    cedula = models.CharField(default='', max_length=20, verbose_name=u"Cedula", blank=True, db_index=True)
    pasaporte = models.CharField(default='', max_length=20, blank=True, verbose_name=u"Pasaporte", db_index=True)
    fecha_nacimiento = models.DateField(verbose_name=u"Fecha de nacimiento o constitución", blank=True, null=True,)
    sexo = models.IntegerField(choices=SEXO, verbose_name=u'Sexo', blank=True, null=True)
    celular = models.CharField(default='', max_length=50, verbose_name=u"Telefono movil")
    telefono = models.CharField(default='', max_length=50, verbose_name=u"Telefono fijo")
    email = models.CharField(default='', max_length=200, verbose_name=u"Correo electrónico personal")
    nacionalidad = models.ForeignKey(Pais,blank=True, null=True,related_name='nacionalidades', on_delete=models.CASCADE, verbose_name="Nacionalidad que tiene el usuario")
    pais = models.ForeignKey(Pais, blank=True, null=True, related_name='+', verbose_name=u'País residencia', on_delete=models.CASCADE)
    provincia = models.ForeignKey(Provincia, blank=True, null=True, related_name='+',verbose_name=u"Provincia de residencia", on_delete=models.CASCADE)
    ciudad = models.ForeignKey(Ciudad, blank=True, null=True, related_name='+', verbose_name=u"Ciudad de residencia", on_delete=models.CASCADE)
    direccion = models.CharField(default='', max_length=300, verbose_name=u"Calle principal")
    foto = models.ImageField(upload_to='users/foto', verbose_name=u'Foto',blank=True, null=True)
    dosfactores = models.BooleanField(default=False, verbose_name='Autenticacion de dos factores')
    codigoacceso = models.CharField(default='', max_length=50, verbose_name=u"Codigo de acceso")
    autenticado = models.BooleanField(default=False, verbose_name='Verificación de acceso')

    def __str__(self):
        return self.nombres_completos_inverso()

    def nombres_completos_inverso(self):
        nombre_completo = f"{self.apellido1} {self.apellido2} {self.nombres}"
        return nombre_completo.title()

    def nombres_completos_lienal(self):
        nombre_completo = f"{self.nombres} {self.apellido1} {self.apellido2}"
        return nombre_completo.title()

    def nombres_simple(self):
        nombre_completo = self.nombres.split()[0].title()
        apellido1 = self.apellido1.title()
        return f"{nombre_completo} {apellido1}"

    def get_avatar_html_40px(self):
        if self.foto:
            return f'<div class="avatar avatar-md avatar-indicators avatar-online"><img alt="avatar" src="{self.foto.url}"class="rounded-circle"/></div>'
        else:
            siglas=self.nombres[0].upper()+self.apellido1[0].upper()
            return f'<div class="siglas-md mt-0 ml-1"> <span class="mt-0">{siglas}</span></div>'

    def get_avatar_img_md(self):
        if self.foto:
            return f'<img src="{self.foto.url}" class="rounded-circle avatar-md me-2"/>'
        else:
            siglas=self.nombres[0].upper()+self.apellido1[0].upper()
            return f'<div class="siglas-md mt-0 ml-1 me-2"> <span class="mt-0">{siglas}</span></div>'

    def get_avatar_img_sm(self):
        if self.foto:
            return f'<img src="{self.foto.url}" class="rounded-circle avatar-sm me-2"/>'
        else:
            siglas=self.nombres[0].upper()+self.apellido1[0].upper()
            return f'<div class="siglas-sm mt-0 ml-1 me-2"> <span class="mt-0">{siglas}</span></div>'

    def get_foto(self):
        return self.foto.url if self.foto else ''

    def to_dict(self):
        persona_dict=model_to_dict(self)
        for key, value in persona_dict.items():
            if isinstance(value, datetime.date):
                persona_dict[key] = value.strftime('%Y-%m-%d')
        return persona_dict

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = Persona.objects.filter((Q(cedula=self.cedula) |
                                    Q(cedula=self.pasaporte) |
                                    Q(pasaporte=self.pasaporte) |
                                    Q(pasaporte=self.cedula) |
                                    Q(usuario__email=self.email) |
                                    Q(email=self.email)), status=True).exclude(pk=self.pk).exclude(pasaporte='',pasaporte__isnull=False).exclude(cedula__isnull=False, cedula='')
        if qs.exists():
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    class Meta:
        verbose_name = u"Persona"
        verbose_name_plural = u"Personas"
        ordering = ['apellido1', 'apellido2', 'nombres']

class UsuariosAcceso(ModeloBase):
    cedula = models.CharField(default='', max_length=20, verbose_name=u"Cedula", blank=True, db_index=True)
    email = models.CharField(default='', max_length=200, verbose_name=u"Correo electrónico personal")
    
    def __str__(self):
        return self.cedula
    
    class Meta:
        verbose_name = u"Usuario Acceso"
        verbose_name_plural = u"Usuarios Acceso"

   

clubes/templates/clubes/integrantes.html
{% extends 'base_admin.html' %}
{% load static %}
{% load extra_tags %}
{% block heading %}{% endblock %}
{% block extra_js %}
    <script type="text/javascript">
        $(function (){
            $("#l_total").text('({{ listado.count }})')
        })
    </script>
{% endblock %}
{% block url_atras %}{{ request.path }}{% endblock %}
{% block enlaces_top %}
    <li class="breadcrumb-item"><a href="{{ request.path }}">Equipos ({{ club|title_cap }})</a></li>
    <li class="breadcrumb-item">{{ title }}</li>
{% endblock %}
{% block botones_top %}
    <div class="nav btn-group" role="tablist">
        <a href="{% url 'clubes:gestion_clubes' %}?action=addintegrante&id={{ club.id|encrypt }}" class="btn btn-success btn-xs btn-xl" title="Adicionar docente" data-bs-toggle="tooltip"> <i class="fas fa-plus"></i> Adicionar</a>
    </div>
{% endblock %}
{% block content_1 %}
    <div class="row mb-3">
        <div class="col-12">
            <h3><i class="fa-brands fa-hubspot"></i> Club de {{ club|title_cap }}</h3>
        </div>
        <form class="col-12" method="GET">
            <!-- Card header -->
            <div class="card-header border-bottom-0 p-0 bg-white">
                <div class="d-flex align-items-center">
                    <span class="position-absolute ps-3 search-icon">
                        <i class="fe fe-search"></i>
                    </span>
                    <input type="hidden" name="action" value="{{ action }}">
                    <input type="hidden" name="id" value="{{ club.id|encrypt }}">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <select name="rol" id="id_rol" class="selectpicker" placeholder="Seleccione un rol a filtrar">
                                <option value=""></option>
                                {% for r in roles %}
                                    <option value="{{ r.0 }}" {% if rol == r.0 %}selected{% endif %}>{{ r.1 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <input type="search" class="form-control ps-6" name="s" placeholder="Buscar por cédula, username, nombres o apellidos..." value="{{ s }}"/>
                        <div class="input-group-append">
                            <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                            {% if url_vars %}
                                <a href="{{ request.path }}?action={{ action }}&id={{ club.id|encrypt }}" class="btn btn-default"><i class="fas fa-refresh"></i></a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div class="row">
        <div class="col-12">
        <div class="card">
            <!-- table -->
            <div class="table-responsive">
                <table class="table mb-0 text-nowrap table-bordered" id="l_table">
                    <thead class="table-light">
                        <tr>
                             <th scope="col" class="text-center w-5">
                                <i class="fas fa-sort-numeric-asc"></i>
                            </th>
                            <th scope="col" class="w-15">
                                Usuario
                            </th>
                            <th scope="col" class="">
                                Detalle
                            </th>
                            <th scope="col" class="text-center w-5">
                                Rol
                            </th>
                            <th scope="col" class="text-center w-5">
                                <i class="fas fa-cogs"></i>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for l in listado %}
                        <tr>
                            <td class="text-center align-middle w-3">{{ forloop.counter }}</td>
                            <td class="align-middle border-top-0 w-20">
                                <div class="d-flex align-items-center">
                                    {{ l.persona.get_avatar_img_md|safe }}
                                    <div class="my-0 lh-15">
                                        <p class="fw-bold"><i class="fas fa-user"></i> {{ l.persona.nombres_completos_lienal }}</p>

                                        <p class=""><i class="fas fa-id-card-clip"></i> {% if l.persona.cedula %} {{ l.persona.cedula }} {% else %}{{ l.persona.pasaporte }} {% endif %}</p>
                                        <p class=""><i class="fas fa-envelope"></i> {{ l.persona.email }}</p>
                                        <p class=""><i class="fas fa-calendar-day"></i> {{ l.persona.fecha_nacimiento|date:'d-m-Y'|default_if_none:'S/F' }}</p>
                                    </h5>
                                </div>
                            </td>

                            <td class="align-middle border-top-0 w-15 lh-15">
                                <p><i class="fa-solid fa-venus-mars"></i> {{ l.persona.get_sexo_display|default_if_none:'S/S' }}</p>
                                <p><i class="fa-solid fa-mobile"></i> {{ l.persona.celular }}</p>
                                <p><i class="fa-brands fa-font-awesome"></i> {{ l.persona.nacionalidad.nacionalidad|title|default_if_none:'S/N' }}</p>
                                <p><i class="fa-solid fa-location-dot"></i> {{ l.persona.ciudad|default_if_none:'S/C' }}</p>
                            </td>
                            <td class="align-middle border-top-0 text-center w-15">
                                <p>{{l.get_rol_display}}
{#                                {% if l.rol == 1 %}#}
{#                                    | {{l.get_tipojugador_display}}#}
{#                                {% endif %}#}
                                </p>
                            </td>
                            <td class="align-middle border-top-0 text-center w-3">
                                <span class="dropdown dropstart">
                                  <a class="btn-icon btn btn-sm rounded-circle" href="#"
                                     role="button"
                                     id="courseDropdown1"
                                     data-bs-toggle="dropdown" data-bs-offset="-20,20"
                                     aria-expanded="false">
                                  <i class="fe fe-more-vertical"></i>
                                  </a>
                                  <span class="dropdown-menu" aria-labelledby="courseDropdown1">
                                  <span class="dropdown-header"><i class="fas fa-cogs"></i> Acciones</span>
                                    <a class="dropdown-item"
                                       href="{{ request.path }}?action=editintegrante&id={{ l.pk|encrypt }}">
                                        <i class="fe fe-edit dropdown-item-icon"></i>Editar
                                    </a>
                                    <a class="dropdown-item" href="javascript:void(0);"
                                         onclick="eliminarajax('{{ l.pk|encrypt }}','{{l}}','delintegrante')">
                                        <i class="fe fe-trash dropdown-item-icon"></i> Eliminar
                                    </a>
                                  </span>
                                </span>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5" class="text-center">No existen registros</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <!-- Pagination -->
                {% include 'paginador.html' %}
            </div>
        </div>
        </div>
    </div>
{% endblock %}