clasificacion_futbol/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path

urlpatterns = [path('admin/', admin.site.urls),
               # CONTROL DE ACCESO USUARIO
               re_path(r'^', include(('users.urls', 'users'), namespace='users')),
               re_path(r'^', include(('clubes.urls', 'clubes'), namespace='clubes')),
               re_path(r'^', include(('core.urls', 'core'), namespace='core')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clubes/urls.py
# Users Urls

# Django
from django.urls import path, re_path

# importaciones de apps
from clubes import gestion_clubes

urlpatterns = [
    # CONTROL USUARIOS
    re_path(r'^gestion_clubes$', gestion_clubes.ViewSet.as_view(), name='gestion_clubes'),
]

core/urls.py
# Users Urls

# Django
from django.urls import path, re_path

# importaciones de apps
from core import api

urlpatterns = [
    # CONTROL USUARIOS
    re_path(r'^api', api.ViewSet.as_view(), name='api'),
]

clubes/models.py
from datetime import datetime

from django.db import models
from django.db.models import Sum, Value, Count
from django.db.models.functions import Coalesce

from core.models import ModeloBase
from users.models import Persona

TIPO_ROL = (
    (1, 'Jugador'),
    (2, 'Director Técnico'),
)
TIPO_JUGADOR = (
    (0, 'No es Jugador'),
    (1, 'Portero'),
    (2, 'Defensa'),
    (3, 'Centrocampista'),
    (4, 'Delantero'),
    (5, 'Suplente'),
    (6, 'Capitán'),
)

TIPO_CLUB = (
    (1, 'Hombres'),
    (2, 'Mujeres')
)
TIEMPOS = (
    (1, 'Primer Tiempo'),
    (2, 'Segundo Tiempo '),
    (3, 'Tiempo Extra Primer Tiempo'),
    (4, 'Tiempo Extra Primer Tiempo'),

)

ESTADO_PARTIDO = (
    (1, 'Planificado'),
    (2, 'Finalizado')
)
# Create your models here.
class Club(ModeloBase):
    nombre = models.CharField(default='', max_length=500, verbose_name=u"Nombre del club")
    descripcion = models.TextField(default='', verbose_name=u"descripción del club")
    tipoequipo = models.IntegerField(choices=TIPO_CLUB, default=1, verbose_name=u'Tipo de equipo')
    escudo = models.ImageField(upload_to='club', verbose_name=u'Escudo del club', blank=True, null=True)
    codigo = models.CharField(default='', blank=True, null=True, verbose_name='Codigo de consulta', max_length=500)
    
    def __str__(self):
        return u'%s' % self.nombre

    def generar_codigo(self):
        nombres = self.nombre.split(' ')
        siglas = ''
        for n in nombres:
            siglas += n[0].upper()
        numero = len(Club.objects.filter(status=True)) + 1
        palabra = f'{siglas}{self.id}{numero}'
        return palabra

    def generar_siglas(self):
        nombres = self.nombre.split(' ')
        siglas = ''
        for n in nombres:
            siglas += n[0].upper()
        palabra = f'{siglas}{self.id}'
        return palabra

    def club_in_torneo(self, idtorneo=None):
        if idtorneo:
            torneo = Torneo.objects.get(id=int(idtorneo))
            return self in torneo.equipos.all()
        return False

    def resultados_torneo(self, torneo):
        resultados = self.resultadopartido_set.filter(status=True, partido__torneo=torneo)
        tarjetas = self.tarjetapartido_set.filter(status=True, partido__torneo=torneo)
        pagorubros=self.pagorubrotarjeta_set.filter(status=True,torneo=torneo, estado=1)
        context = {'total_partidos': len(resultados),
                   'total_puntos': resultados.aggregate(totalpuntos=Coalesce(Sum('puntos'), Value(0)))['totalpuntos'],
                   'total_tarjetas': len(tarjetas),
                   'tarjeta': tarjetas.values('tipotarjeta__nombre').annotate(conteo=Count('id')),
                   'pendiente_pagar': tarjetas.filter(pagado=False).aggregate(totalpagar=Coalesce(Sum('valor'), Value(0.00)))['totalpagar'],
                   'total_pagado': tarjetas.filter(pagado=True).aggregate(totalpagar=Coalesce(Sum('valor'), Value(0.00)))['totalpagar'],
                   'total': tarjetas.aggregate(totalpagar=Coalesce(Sum('valor'), Value(0.00)))['totalpagar'],
                   'pagorubros': pagorubros
                   }
        return context

    def tarjetas_pagar(self, torneo):
        tarjetas = self.tarjetapartido_set.filter(status=True, partido__torneo=torneo, pagado=False)
        return {'tarjetas':tarjetas,'pendiente_pagar': tarjetas.aggregate(totalpagar=Coalesce(Sum('valor'), Value(0.00)))['totalpagar']}
    
    def total_integrantes(self):
        return self.integranteclub_set.filter(status=True)

    def siglas(self):
        nombre = self.nombre.split(' ')
        if len(nombre) == 1:
            siglas = self.nombre[0].upper() + self.nombre[-1].upper()
        else:
            siglas = nombre[0][0].upper() + nombre[1][0].upper()
        return siglas

    def get_escudo_html_40px(self):
        if self.escudo:
            return f'<div class="avatar avatar-md avatar-indicators avatar-online"><img alt="avatar" src="{self.escudo.url}"class="rounded-circle"/></div>'
        else:
            return f'<div class="siglas-md mt-0 ml-1"> <span class="mt-0 bg-secondary">{self.siglas()}</span></div>'

    def get_escudo_img_md(self):
        if self.escudo:
            return f'<img src="{self.escudo.url}" class="rounded-circle avatar-md me-2"/>'
        else:
            return f'<div class="siglas-md mt-0 ml-1 me-2"> <span class="mt-0 bg-secondary">{self.siglas()}</span></div>'

    def get_escudo_img_sm(self):
        if self.escudo:
            return f'<img src="{self.escudo.url}" class="rounded-circle avatar-xs me-2"/>'
        else:
            return f'<img src="/static/images/escudo.png" class="avatar-xs me-2"/>'

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = Club.objects.filter(nombre=self.nombre, status=True).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    def resultado_partido(self, partido):
        resultado = self.resultadopartido_set.filter(status=True, partido=partido).first()
        return resultado

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()
        super(Club, self).save(*args, **kwargs)

    class Meta:
        verbose_name = u"Club"
        verbose_name_plural = u"Clubes"
        ordering = ['nombre']


class IntegranteClub(ModeloBase):
    club = models.ForeignKey(Club, on_delete=models.CASCADE, verbose_name=u"Club")
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE, verbose_name=u"Club")
    rol = models.IntegerField(choices=TIPO_ROL, default=1, verbose_name=u'Tipo de rol en el club')
    tipojugador = models.IntegerField(choices=TIPO_JUGADOR, default=0, verbose_name=u'Tipo de jugador en el club')
    suspendido = models.BooleanField(default=False, verbose_name=u'Integrante suspendido')
    
    def __str__(self):
        return f'{self.persona}'

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = IntegranteClub.objects.filter(status=True, club=self.club, persona=self.persona).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    class Meta:
        verbose_name = u"Integrante del club"
        verbose_name_plural = u"Integrantes del club"
        ordering = ['persona']


class Fase(ModeloBase):
    nombre = models.CharField(default='', max_length=500, verbose_name=u"Nombre de la fase")
    descripcion = models.TextField(default='', blank=True, null=True, verbose_name=u"descripción de la fase")

    def __str__(self):
        return f'{self.nombre}'

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = Fase.objects.filter(status=True, nombre=self.nombre).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    class Meta:
        verbose_name = u"Fase"
        verbose_name_plural = u"Fases"
        ordering = ['nombre']


class TipoPartido(ModeloBase):
    nombre = models.CharField(default='', max_length=500, verbose_name=u"Nombre del partido")
    descripcion = models.TextField(default='', blank=True, null=True, verbose_name=u"descripción del partido")

    def __str__(self):
        return f'{self.nombre}'

    def tipomarcado(self, torneo=False):
        if torneo:
            return torneo.tipopartidos.filter(id=self.id).exists()
        return torneo

    def fases(self):
        return self.tipopartidofase_set.filter(status=True)

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = TipoPartido.objects.filter(status=True, nombre=self.nombre).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    class Meta:
        verbose_name = u"Tipo Partido"
        verbose_name_plural = u"Tipos Partidos"
        ordering = ['nombre']


class TipoPartidoFase(ModeloBase):
    tipopartido = models.ForeignKey(TipoPartido, on_delete=models.CASCADE, verbose_name=u"Partido", )
    fase = models.ForeignKey(Fase, on_delete=models.CASCADE, verbose_name=u"Fase", )
    puntos = models.IntegerField(default=3, verbose_name=u"Puntos por partido")
    orden = models.IntegerField(default=0, verbose_name=u"Orden")

    def __str__(self):
        return f'{self.tipopartido}-{self.fase}'

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = TipoPartidoFase.objects.filter(status=True, tipopartido=self.tipopartido, fase=self.fase).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    class Meta:
        verbose_name = u"Fase de Partido"
        verbose_name_plural = u"Fases de Partidos"
        ordering = ['orden']


class Torneo(ModeloBase):
    nombre = models.CharField(default='', max_length=500, verbose_name=u"Nombre del torneo")
    tipopartidos = models.ManyToManyField(TipoPartido, verbose_name="Tipos de partidos que se jugaran")
    generotorneo = models.IntegerField(choices=TIPO_CLUB, default=1, verbose_name="genero de participantes")
    equipos = models.ManyToManyField(Club, verbose_name='Equipos que participan en el torneo')
    inicio = models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio del torneo')
    fin = models.DateTimeField(blank=True, null=True, verbose_name='Fecha que finaliza el torneo')
    
    def __str__(self):
        return f'{self.nombre}-{self.get_generotorneo_display()}'

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = Torneo.objects.filter(status=True, nombre=self.nombre).exclude(pk=self.pk).exists()
        if qs:
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

users/models/models_address.py
from django.db import models
from django.utils.text import slugify

from core.models import ModeloBase

class Pais(ModeloBase):
    nombre = models.CharField(default='', max_length=100, verbose_name=u"Nombre")
    nacionalidad = models.CharField(default='', max_length=100, verbose_name=u"Nacionalidad")
    codigonacionalidad = models.CharField(max_length=10, default="", verbose_name=u"Código nacionalidad")
    codigo = models.IntegerField(default=0, verbose_name=u"Código de pais")

    def __str__(self):
        return u'%s' % self.nombre

    def provincias(self):
        return self.provincia_set.filter(status=True)

    class Meta:
        verbose_name = u"País"
        verbose_name_plural = u"Paises"
        ordering = ['nombre']
        unique_together = ('nombre',)

    def en_uso(self):
        return self.provincia_set.filter(status=True).values('id').exists()

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()
        self.nacionalidad = self.nacionalidad.upper()
        self.codigonacionalidad = self.codigonacionalidad.upper()
        super(Pais, self).save(*args, **kwargs)

class Provincia(ModeloBase):
    pais = models.ForeignKey(Pais, blank=True, null=True, verbose_name=u'País', on_delete=models.CASCADE)
    nombre = models.CharField(default='', max_length=100, verbose_name=u"Nombre")
    codigo = models.IntegerField(default=0, verbose_name=u"Código de provincia")

    def __str__(self):
        return u'%s' % self.nombre

    def ciudades(self):
        return self.ciudad_set.filter(status=True)

    class Meta:
        verbose_name = u"Provincia"
        verbose_name_plural = u"Provincias"
        ordering = ['nombre']
        unique_together = ('nombre', 'pais')

    def en_uso(self):
        return self.canton_set.values('id').all().exists()

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()
        super(Provincia, self).save(*args, **kwargs)

class Ciudad(ModeloBase):
    codigo = models.CharField(max_length=200, verbose_name='Código de ciudad', blank=True, null=True)
    provincia = models.ForeignKey(Provincia, on_delete=models.PROTECT)
    nombre = models.CharField(max_length=200, verbose_name='Ciudad')
    lat = models.CharField(max_length=200, default='', blank=True, null=True, verbose_name='Latitud')
    long = models.CharField(max_length=200, default='', blank=True, null=True, verbose_name='Longitud')

    def __str__(self):
        return "{}".format(self.nombre)
        # return "{}, {}, {}".format(self.nombre, self.provincia.nombre, self.provincia.pais.nombre)

    class Meta:
        verbose_name = 'Ciudad'
        verbose_name_plural = 'Ciudades'
        ordering = ('nombre',)

    def save(self, force_insert=False, force_update=False, using=None, **kwargs):
        self.nombre = self.nombre.upper()
        self.nombre_st = slugify(self.nombre).replace('-', ' ')
        super(Ciudad, self).save(force_insert, force_update, using)

clubes/templates/clubes/formularios/formgoles.html
{% extends 'base_ajax_form_modal.html' %}
{% load extra_tags %}
{% block section_form %}
    <div class="col-12 mt-2">
        <div class="row">
             <div class="col-12 col-md-9 ">
                <h5><i class="fa fa-users dropdown-item-icon"></i>Equipos</h5>
            </div>
            <div class="col-12 col-md-3 text-center">
                <h5><i class="fa fa-futbol dropdown-item-icon"></i>Goles</h5>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12 col-md-9">
                <h5>{{ partido.clublocal.get_escudo_img_sm|safe }}
                    {{ partido.clublocal|title_cap }}
                </h5>
            </div>
            <div class="col-12 col-md-3">
                <input type="number" name="goleslocal" class="form-control text-center w-100 soloNumeros" value="{{ partido.goleslocal }}" min="0"
                       required>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-12 col-md-9">
                <h5>{{ partido.clubvisitante.get_escudo_img_sm|safe }}
                    {{ partido.clubvisitante|title_cap }}
                </h5>
            </div>
            <div class="col-12 col-md-3">
                <input type="number" name="golesvisitante" class="form-control text-center w-100 soloNumeros" value="{{ partido.golesvisitante }}" min="0"
                       required>
            </div>
        </div>
    </div>
{% endblock %}

clubes/templates/clubes/formularios/formintegrantes.html
{% extends 'base_ajax_form.html' %}
{% load extra_tags %}
{% block heading_1 %}

{% endblock %}
{% block extra_js_1 %}
    <script>
        $(function (){
            let pais = $("#id_pais")
            let provincia = $("#id_provincia")
            let ciudad = $("#id_ciudad")
            {% if not integrante or not integrante.rol == 1 %}
                $("#col_tipojugador").hide()
            {% endif %}
            $("#id_cedula").change(function (){
                console.log('hola')
                $("#errorFieldcedula").text('')
                let validar=validarCedula(this.value)
                if (!validar){
                    $("#errorFieldcedula").text("Cédula incorrecta")
                }
            })
            $("#id_rol").on('change', function (){
                if ($(this).val()==1){
                    $("#col_tipojugador").show()
                     $("#id_tipojugador").attr('required',true)
                }else{
                    $("#col_tipojugador").hide()
                    $("#id_tipojugador").attr('required',false)
                }
            })
            provincia.change(function (){
                ciudad.empty()
            })
            cargarSelectSecundario('cargarprovincias',pais,provincia,'/api')
            cargarSelectSecundario('cargarciudades',provincia,ciudad,'/api')
        });
    </script>
{% endblock %}
{% block url_atras %}{{ request.path }}?action=integrantes&id={{ club.id|encrypt }}{% endblock %}
{% block enlaces_top %}
    <li class="breadcrumb-item"><a href="{{ request.path }}">Clubes ({{ club|title_cap }})</a></li>
    <li class="breadcrumb-item"><a href="{{ request.path }}?action=integrantes&id={{ club.id|encrypt }}">Integrantes</a></li>
    <li class="breadcrumb-item">{{ title }}</li>
{% endblock %}
{% block head_title %}
    {{ title }} de club ({{ club|title_cap }})
{% endblock %}

clubes/templates/clubes/formularios/pagosrubros.html
{% extends 'base_ajax_form_modal.html' %}
{% load extra_tags %}
{% block section_form %}
    <div class="col-lg-6">
        <h5 class=""><i class="fas fa-sheet-plastic"></i> Tarjetas pagadas</h5>
        <div class="table-responsive mb-6">
            <table class="table mb-0 text-nowrap table-bordered" id="l_table">
                <thead class="">
                <tr>
                    <th scope="col" class="text-center">
                        <i class="fe fe-check"></i>
                    </th>
                    <th scope="col" class="text-center">
                        Jugador
                    </th>
                    <th scope="col" class="text-center">
                        Tarjeta
                    </th>
                    <th scope="col" class="text-center">
                        Valor
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for l in tarjetas %}
                    <tr>
                        <td class="text-center w-3">
                            <input type="checkbox" class="tarjeta" name="tarjetas" value="{{l.id}}" checked>
                        </td>
                        <td class="text-center align-middle w-50">
                            {{ l.integrante.persona|title_cap }}
                        </td>
                        <td class="align-middle border-top-0 lh-15 w-15">
                        {{ l.tipotarjeta }}
                        </td>
                        <td class="text-center align-middle">
                            $ <span class="valor">{{l.valor}}</span>
                        </td>
                    
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" class="text-center">No existen registros</td>
                    </tr>
                {% endfor %}
                    <tr>
                        <td colspan="3" class="text-end fw-semi-bold">Total</td>
                        <td class="text-center" id="id_total"></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="">
            <h5><i class="fas fa-list"></i> Detalle</h5>
            <div class="ms-3">
                <p><span class="fw-semi-bold">Fecha: </span>{{pago.fecha_creacion|date:'d-m-Y | H:i'}}</p>
                <p><span class="fw-semi-bold">Valor pagado: </span>${{pago.valor}}</p>
                <p><span class="fw-semi-bold">Comprobante: </span> <a href="{{pago.archivo.url}}" target="_blank" class="text-secondary"><i class="fe fe-eye text-success"></i> Ver comprobante</a></p>    
            </div>
        
            <h5 class="mt-3"><i class="fe fe-check-circle"></i> Validar comprobante</h5>
            <div class="mt-2 ms-3">
                <label for=""><i class="fa-solid fa-traffic-light"></i> Estado <span class="fw-semi-bold text-danger">*</span>:</label>
                <select name="estado" id="id_estado" class="select2">
                    <option value="2" {% if pago.estado == 2 %}selected{% endif %}>Aprobado</option>
                    <option value="3" {% if pago.estado == 3 %}selected{% endif %}>Rechazado</option>
                </select>
            </div>
            <div class="mt-2 ms-3">
                <label for=""><i class="fas fa-commenting"></i> Observación:</label>
            <textarea name="observacion" id="id_observacion" rows="3" placeholder="Describa una obsevacion..." class="form-control">{{ pago.observacion }}</textarea>
            </div>
        </div>
        
    </div>
{% endblock %}
{% block extra_js_modal %}
<script>
    $(function(){
        let total=calcularSuma()
        $("#id_total").text('$ '+total) 
        $(".tarjeta").change(function(){
            total=calcularSuma()
            $("#id_total").text('$ '+total) 
        })
    })
//     function calcularSuma() {
//     // Obtener todas las celdas con la clase "valor"
//     var celdas = document.getElementsByClassName("valor");
    
//     // Inicializar la suma
//     var suma = 0;

//     // Iterar sobre las celdas y sumar sus valores convertidos a números
//     for (var i = 0; i < celdas.length; i++) {
//       suma += parseFloat(celdas[i].textContent) || 0;
//     }
//     console.log(suma)
//     // Mostrar la suma en la consola o en algún otro lugar
//     return suma
//   }
  function calcularSuma() {
        var checkboxes = document.getElementsByName("tarjetas");
        var suma = 0;

        for (var i = 0; i < checkboxes.length; i++) {
            if (checkboxes[i].checked) {
                var valorElement = checkboxes[i].closest('tr').querySelector('.valor');
                suma += parseFloat(valorElement.innerText) || 0;
            }
        }
        return suma
        // Mostrar la suma en la consola o en algún otro lugar
        // console.log("Suma total:", suma);
    }
</script>
{% endblock %}

clubes/templates/clubes/formularios/resultados.html
{% load extra_tags %}
<div class="col-lg-6">
    <div class="text-center">
        <h5>{{ partido.clublocal.get_escudo_img_sm|safe }} {{ partido.clublocal }}</h5>
    </div>
    <h5 class=""><i class="fas fa-futbol"></i> Goles</h5>
    <div class="table-responsive mb-6">
        <table class="table mb-0 text-nowrap table-bordered" id="l_table">
            <thead class="">
            <tr>
                <th scope="col" class="text-center">
                    Minutos
                </th>
                <th scope="col" class="text-center">
                    Jugador
                </th>
                <th scope="col" class="text-center">
                    Gol
                </th>
                <th scope="col" class="text-center">

                </th>
            </tr>
            </thead>
            <tbody>
            {% for l in partido.goles_l %}
                <tr>
                    <td class="text-center align-middle w-3">
                        <p>{{ l.minuto }}</p>
                    </td>
                    <td class="align-middle border-top-0 lh-15 w-50">
                        {{ l.integrante.persona|title_cap }}
                    </td>
                    <td class="text-center align-middle">
                        {{ l.cantidad }}
                    </td>
                    <td class="align-middle w-3">
                        <a href="javascript:void(0)"
                           onclick="eliminarajax('{{ l.id|encrypt }}','{{ l.persona }}','delgol')"
                           class="text-danger"><i class="fe fe-trash"></i></a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5" class="text-center">No existen registros</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <h5 class=""><i class="fas fa-sheet-plastic"></i> Tarjetas</h5>
    <div class="table-responsive mb-6">
        <table class="table mb-0 text-nowrap table-bordered" id="l_table">
            <thead class="">
            <tr>
                <th scope="col" class="text-center">
                    Minutos
                </th>
                <th scope="col" class="text-center">
                    Jugador
                </th>
                <th scope="col" class="text-center">
                    Tarjeta
                </th>
                <th scope="col" class="text-center">

                </th>
            </tr>
            </thead>
            <tbody>
            {% for l in partido.tarjetas_local %}
                <tr>
                    <td class="text-center align-middle w-3">
                        <p>{{ l.get_tiempo_display }}</p>
                        <p>{{ l.minuto }}</p>
                    </td>
                    <td class="align-middle border-top-0 lh-15 w-50">
                        {{ l.integrante.persona|title_cap }}
                    </td>
                    <td class="text-center align-middle">
                        {{ l.cantidad }} {{ l.tipotarjeta }}
                    </td>
                    <td class="align-middle w-3">
                        <a href="javascript:void(0)"
                           onclick="eliminarajax('{{ l.id|encrypt }}','{{ l.persona }}','deltarjeta')"
                           class="text-danger"><i class="fe fe-trash"></i></a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5" class="text-center">No existen registros</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="col-lg-6">
    <div class="text-center">
        <h5>{{ partido.clubvisitante.get_escudo_img_sm|safe }} {{ partido.clubvisitante }}</h5>
    </div>
    <h5 class=""><i class="fas fa-futbol"></i> Goles</h5>
    <div class="table-responsive mb-6">
        <table class="table mb-0 text-nowrap table-bordered" id="l_table">
            <thead class="">
            <tr>
                <th scope="col" class="text-center">
                    Minutos
                </th>
                <th scope="col" class="text-center">
                    Jugador
                </th>
                <th scope="col" class="text-center">
                    Gol
                </th>
                <th scope="col" class="text-center">

                </th>
            </tr>
            </thead>
            <tbody>
            {% for l in partido.goles_v %}
                <tr>
                    <td class="text-center align-middle w-3">
                        <p>{{ l.minuto }}</p>
                    </td>
                    <td class="align-middle border-top-0 lh-15 w-50">
                        {{ l.integrante.persona|title_cap }}
                    </td>
                    <td class="text-center align-middle">
                        {{ l.cantidad }}
                    </td>
                    <td class="align-middle w-3">
                        <a href="javascript:void(0)"
                           onclick="eliminarajax('{{ l.id|encrypt }}','{{ l.persona }}','delgol')"
                           class="text-danger"><i class="fe fe-trash"></i></a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5" class="text-center">No existen registros</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
     <h5 class=""><i class="fas fa-sheet-plastic"></i> Tarjetas</h5>
    <div class="table-responsive mb-6">
        <table class="table mb-0 text-nowrap table-bordered" id="l_table">
            <thead class="">
            <tr>
                <th scope="col" class="text-center">
                    Minutos
                </th>
                <th scope="col" class="text-center">
                    Jugador
                </th>
                <th scope="col" class="text-center">
                    Tarjeta
                </th>
                <th scope="col" class="text-center">

                </th>
            </tr>
            </thead>
            <tbody>
            {% for l in partido.tarjetas_visitante %}
                <tr>
                    <td class="text-center align-middle w-3">
                        <p>{{ l.get_tiempo_display }}</p>
                        <p>{{ l.minuto }}</p>
                    </td>
                    <td class="align-middle border-top-0 lh-15 w-50">
                        {{ l.integrante.persona|title_cap }}
                    </td>
                    <td class="text-center align-middle">
                        {{ l.cantidad }} {{ l.tipotarjeta }}
                    </td>
                    <td class="align-middle w-3">
                        <a href="javascript:void(0)"
                           onclick="eliminarajax('{{ l.id|encrypt }}','{{ l.persona }}','deltarjeta')"
                           class="text-danger"><i class="fe fe-trash"></i></a>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5" class="text-center">No existen registros</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>