clasificacion_futbol/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path

urlpatterns = [path('admin/', admin.site.urls),
               # CONTROL DE ACCESO USUARIO
               re_path(r'^', include(('users.urls', 'users'), namespace='users')),
               re_path(r'^', include(('clubes.urls', 'clubes'), namespace='clubes')),
               re_path(r'^', include(('core.urls', 'core'), namespace='core')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# Users Urls

# Django
from django.urls import path, re_path

# importaciones de apps
from core import api

urlpatterns = [
    # CONTROL USUARIOS
    re_path(r'^api', api.ViewSet.as_view(), name='api'),
]

users/urls.py
# Users Urls

# Django
from django.urls import path, re_path

# importaciones de apps
from users import control_acceso, adm_panel, adm_users

urlpatterns = [
    # PANTALLAS PRINCIPALES
    re_path(r'^$',adm_panel.HomeView.as_view(), name='home'),
    re_path(r'^main$', adm_panel.MainView.as_view(), name='main'),

    # ACCESO AL SISTEMA
    re_path(r'^login$',control_acceso.LoginView.as_view(), name='login'),
    re_path(r'^signup$',control_acceso.SignupView.as_view(), name='signup'),
    re_path(r'^logout$',control_acceso.LogoutView.as_view(), name='logout'),
    re_path(r'^validate_token$', control_acceso.validate_token, name='validate_token'),

    # CONTROL USUARIOS
    re_path(r'^usuarios$', adm_users.ViewSet.as_view(), name='usuarios'),

    # re_path(r'^administrativos$', administrativos.ViewSet.as_view(), name='administrativos'),
    # # re_path(r'^estudiantes$', estudiantes.ViewSet.as_view(), name='estudiantes'),
    # re_path(r'^docentes$', docentes.ViewSet.as_view(), name='docentes'),
]

users/models/models_address.py
from django.db import models
from django.utils.text import slugify

from core.models import ModeloBase

class Pais(ModeloBase):
    nombre = models.CharField(default='', max_length=100, verbose_name=u"Nombre")
    nacionalidad = models.CharField(default='', max_length=100, verbose_name=u"Nacionalidad")
    codigonacionalidad = models.CharField(max_length=10, default="", verbose_name=u"Código nacionalidad")
    codigo = models.IntegerField(default=0, verbose_name=u"Código de pais")

    def __str__(self):
        return u'%s' % self.nombre

    def provincias(self):
        return self.provincia_set.filter(status=True)

    class Meta:
        verbose_name = u"País"
        verbose_name_plural = u"Paises"
        ordering = ['nombre']
        unique_together = ('nombre',)

    def en_uso(self):
        return self.provincia_set.filter(status=True).values('id').exists()

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()
        self.nacionalidad = self.nacionalidad.upper()
        self.codigonacionalidad = self.codigonacionalidad.upper()
        super(Pais, self).save(*args, **kwargs)

class Provincia(ModeloBase):
    pais = models.ForeignKey(Pais, blank=True, null=True, verbose_name=u'País', on_delete=models.CASCADE)
    nombre = models.CharField(default='', max_length=100, verbose_name=u"Nombre")
    codigo = models.IntegerField(default=0, verbose_name=u"Código de provincia")

    def __str__(self):
        return u'%s' % self.nombre

    def ciudades(self):
        return self.ciudad_set.filter(status=True)

    class Meta:
        verbose_name = u"Provincia"
        verbose_name_plural = u"Provincias"
        ordering = ['nombre']
        unique_together = ('nombre', 'pais')

    def en_uso(self):
        return self.canton_set.values('id').all().exists()

    def save(self, *args, **kwargs):
        self.nombre = self.nombre.upper()
        super(Provincia, self).save(*args, **kwargs)

class Ciudad(ModeloBase):
    codigo = models.CharField(max_length=200, verbose_name='Código de ciudad', blank=True, null=True)
    provincia = models.ForeignKey(Provincia, on_delete=models.PROTECT)
    nombre = models.CharField(max_length=200, verbose_name='Ciudad')
    lat = models.CharField(max_length=200, default='', blank=True, null=True, verbose_name='Latitud')
    long = models.CharField(max_length=200, default='', blank=True, null=True, verbose_name='Longitud')

    def __str__(self):
        return "{}".format(self.nombre)
        # return "{}, {}, {}".format(self.nombre, self.provincia.nombre, self.provincia.pais.nombre)

    class Meta:
        verbose_name = 'Ciudad'
        verbose_name_plural = 'Ciudades'
        ordering = ('nombre',)

    def save(self, force_insert=False, force_update=False, using=None, **kwargs):
        self.nombre = self.nombre.upper()
        self.nombre_st = slugify(self.nombre).replace('-', ' ')
        super(Ciudad, self).save(force_insert, force_update, using)

users/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.hashers import check_password
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.db.models import Q
from django.core import validators
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
# models
from django.contrib.auth.models import User

from clubes.models import TIPO_ROL, TIPO_JUGADOR, Club, Torneo
from core.forms import FormBase, FormBaseUser, deshabilitar_campo
from core.funciones import generar_username
from core.validators import SoloLetras, v_cedulaform
from users.models import SEXO, Pais, PERFIL_USUARIO
from users.models.models_profile import UsuariosAcceso


class LoginForm(forms.Form):
    email = forms.CharField(label='Correo electrónico o nombre de usuario', widget=forms.TextInput())
    password = forms.CharField(label='Contraseña', max_length=70, widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages = {'required': f'Este campo es requerido'}

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = cleaned_data.get('email').lower()
        password = cleaned_data.get('password')
        if not User.objects.filter(Q(email=email) | (Q(username=email))).exists():
            self.add_error('email', 'No existe usuario con los datos ingresado.')
        else:
            usuario = User.objects.get(Q(email=email) | (Q(username=email)))
            cleaned_data['username'] = usuario.username
            if not usuario.is_active:
                self.add_error('email', 'Este usuario ha sido desactivado.')
            elif not check_password(password, usuario.password):
                self.add_error('password', 'Contraseña incorrecta.')
        return self.cleaned_data


class SignupForm(FormBaseUser):
    cedula = forms.CharField(label=u"Cédula", max_length=10, required=False,
                             widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingresa tu numero de cédula', 'class': 'soloNumeros'}))
    nombres = forms.CharField(label=u'Nombres', max_length=100, required=True,
                              widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingra tus nombres completos', 'class': 'soloLetrasET'}))
    apellido1 = forms.CharField(label=u"Primer apellido", max_length=50, required=True,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingresa tu primer apellido', 'class': 'soloLetrasET'}))
    apellido2 = forms.CharField(label=u"Segundo apellido", max_length=50, required=True,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingresa tu segundo apellido', 'class': 'soloLetrasET'}))
    fecha_nacimiento = forms.DateField(label=u'Fecha nacimiento', required=True,
                                       widget=forms.DateTimeInput(attrs={'col': '6'}))
    nacionalidad = forms.ModelChoiceField(label=u'Nacionalidad', required=False,
                                          queryset=Pais.objects.filter(status=True),
                                          widget=forms.Select(attrs={'col': '6'}))
    celular = forms.CharField(label=u"Teléfono celular", max_length=50, required=False,
                              widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingresa tu telefono celular', 'class': 'soloNumeros'}))
    email = forms.CharField(label=u"Correo electrónico", max_length=200, required=True,
                            widget=forms.EmailInput(attrs={'col': '6', 'placeholder': 'Ingresa tu correo electrónico'}))
    password = forms.CharField(label="Contraseña", max_length=70, widget=forms.PasswordInput(attrs={'col': '6', 'placeholder': 'Ingresa tu contraseña'}))
    password_confirmation = forms.CharField(label="Confirmar contraseña", max_length=70, widget=forms.PasswordInput(attrs={'col': '6', 'placeholder': 'Ingresa tu contraseña'}))

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)

    def clean(self):
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if 'cedula' in data and 'email' in data:
            cedula = data['cedula']
            email = data['email']
            ua=UsuariosAcceso.objects.filter(cedula=cedula, email=email, status=True).exists()
            if not ua:
                self.add_error('cedula','Usuario con los datos proporcionado no tienen permiso de registro')
                self.add_error('email','Usuario con los datos proporcionado no tienen permiso de registro')
        if len(password) >= 6:
            if password.islower() or password.isupper():
                msg = "La contraseña tiene que tener por lo menos 1 letra mayuscula y 1 minuscula"
                self.add_error('password', msg)
            if password.isdigit() or password.isalpha():
                msg = "La contraseña tiene que contener números, letras y caracteres especiales"
                self.add_error('password', msg)
        else:
            msg = "La contraseña tiene que tener como minimo 6 dígitos"
            self.add_error('password', msg)

        if password != password_confirmation:
            msg = "Contraseña no coincide"
            self.add_error('password_confirmation', msg)
        return data


class UsuarioForm(FormBaseUser):
    nombres = forms.CharField(label=u'Nombres', max_length=100, required=True,
                              widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese los nombres del administrativo', 'class': 'soloLetrasET'}))
    apellido1 = forms.CharField(label=u"Primer apellido", max_length=50, required=True,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese el primer apellido del administrativo', 'class': 'soloLetrasET'}))
    apellido2 = forms.CharField(label=u"Segundo apellido", max_length=50, required=True,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese el segundo apellido del administrativo', 'class': 'soloLetrasET'}))
    cedula = forms.CharField(label=u"Cédula", max_length=10, required=False,
                             widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese la cédula del administrativo', 'class': 'soloNumeros'}))
    fecha_nacimiento = forms.DateField(label=u'Fecha nacimiento', required=True,
                                       widget=forms.DateTimeInput(attrs={'col': '6'}))
    pasaporte = forms.CharField(label=u"Pasaporte", max_length=13, required=False,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese el pasaporte del administrativo'}))
    celular = forms.CharField(label=u"Teléfono celular", max_length=50, required=True,
                              widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese el teléfono celular del administrativo', 'class': 'soloNumeros'}))
    telefono = forms.CharField(label=u"Teléfono", max_length=50, required=False,
                               widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese el teléfono del administrativo (opcional)', 'class': 'soloNumeros'}))
    email = forms.CharField(label=u"Correo electrónico", max_length=200, required=True,
                            widget=forms.EmailInput(attrs={'col': '6', 'placeholder': 'Ingrese el correo electrónico del administrativo'}))
    sexo = forms.ChoiceField(label=u"Genero", required=True,
                             choices=SEXO,
                             widget=forms.Select(attrs={'col': '6'}))
    nacionalidad = forms.ModelChoiceField(label=u'Nacionalidad', required=False,
                                          queryset=Pais.objects.filter(status=True),
                                          widget=forms.Select(attrs={'col': '6'}))
    perfil = forms.ChoiceField(label=u'Perfil', required=True,
                               choices=PERFIL_USUARIO[1:4],
                               widget=forms.Select(attrs={'col': '6'}))
    direccion = forms.CharField(label=u"Dirección de domicilio", max_length=50, required=False,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese su dirección de calle principal'}))
    foto = forms.ImageField(label="Foto", required=False, widget=forms.FileInput(attrs={'col': '6'}))

    def edit(self):
        deshabilitar_campo(self, 'email')
        if self.instancia:
            cedula = getattr(self.instancia, 'cedula', None)
            pasaporte = getattr(self.instancia, 'pasaporte', None)
            if cedula:
                deshabilitar_campo(self, 'cedula')
            if pasaporte:
                deshabilitar_campo(self, 'pasaporte')

class UsuarioPermisoForm(FormBase):
    cedula = forms.CharField(label=u"Cédula", max_length=10, required=True,
                             widget=forms.TextInput(attrs={'col': '12', 'placeholder': 'Ingrese la cédula del administrativo', 'class': 'soloNumeros'}))
    email = forms.CharField(label=u"Correo electrónico", max_length=200, required=True,
                            widget=forms.EmailInput(attrs={'col': '12', 'placeholder': 'Ingrese el correo electrónico del administrativo'}))

    def clean(self):
       cleaned_data = super().clean()
       cedula=cleaned_data.get('cedula')
       email=cleaned_data.get('email')
       v_cedulaform(self, cedula, 'cedula')
       id = getattr(self.instancia, 'id', 0)

       ua=UsuariosAcceso.objects.filter(Q(cedula=cedula) | Q(email=email),status=True).exclude(id=id).exists()
       if ua:
           self.add_error('email', 'Registro que intenta agregar ya se encuentra creado')

users/templates/control_acceso/sign-in.html
{% extends 'base.html' %}
{% load static %}
{% block content_js %}
<script type="text/javascript" src="{% static 'js/formquestion.js' %}"></script>
{% endblock %}
<!-- Page content -->
{% block content %}
<div class="container d-flex flex-column">
  <div class="row align-items-center justify-content-center g-0 min-vh-100">

    <div class="col-lg-5 col-md-8 py-8 py-xl-0">
      <!-- Card -->
      <div class="card shadow ">
        <!-- Card body -->
        <div class="card-body p-6">
          <div class="mb-4">
            <a href="../index.html"><img src="../assets/images/brand/logo/logo-icon.svg" class="mb-4" alt=""></a>
            <h1 class="mb-1 fw-bold">Iniciar sesión</h1>
            <!-- <span>¿No estas registrado? <a href="{% url 'users:signup' %}" class="ms-1">Registrate</a></span> -->
          </div>
          <!-- <div>
            <span class="text-danger" id="message_top"><i class="fas fa-info-circle"></i></span>
          </div> -->
          <!-- Form -->
          <form class="sign-in-form form-s" autocomplete="off" method="POST" enctype="multipart/form-data"
            action="{{ request.path }}">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
              <label for="email" class="form-label">{{ field.label}} <b class="text-danger">*</b>:</label>
              <input type="{{ field.widget_type }}" id="email" class="form-control" name="{{ field.name }}"
                placeholder="Ingrese su {{ field.label|lower }}" required>
              <span class="text-danger errorField" id="errorField{{ field.name }}"></span>
            </div>
            <!-- Checkbox -->
            {% endfor %}
            <!-- <div class="d-lg-flex justify-content-between align-items-center mb-4">
                    <div class="form-check">
                      <input type="checkbox" class="form-check-input" id="rememberme">
                      <label class="form-check-label " for="rememberme">Recordar</label>
                    </div>
                    <div>
                      <a href="forget-password.html">¿Olvidaste tu contraseña?</a>
                    </div>
                  </div> -->
            <div>
              <!-- Button -->
              <div class="d-grid">
                <button type="submit" class="btn btn-primary">Iniciar Sesión</button>
              </div>
            </div>
            <hr class="my-4">
            <div class="mt-4 text-center">
              <!--Facebook-->
              <a href="#" class="btn-social btn-social-outline btn-facebook">
                <i class="mdi mdi-facebook fs-4"></i>
              </a>
              <!--Twitter-->
              <a href="#" class="btn-social btn-social-outline btn-twitter">
                <i class="mdi mdi-twitter fs-4"></i>
              </a>
              <!--LinkedIn-->
              <a href="#" class="btn-social btn-social-outline btn-linkedin">
                <i class="mdi mdi-linkedin"></i>
              </a>
              <!--GitHub-->
              <a href="#" class="btn-social btn-social-outline btn-github">
                <i class="mdi mdi-github"></i>
              </a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

users/templates/control_acceso/sign-up.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Page content -->
    <div class="container d-flex flex-column">
        <div class="row align-items-center justify-content-center g-0 min-vh-100">
            <div class="col-lg-7 col-md-8 py-8 py-xl-0">
                <!-- Card -->
                <div class="card shadow">
                    <!-- Card body -->
                    <div class="card-body p-6">
                        <div class="mb-4">
                            <a href="../index.html"><img src="../assets/images/brand/logo/logo-icon.svg" class="mb-4"
                                                         alt=""/></a>
                            <h1 class="mb-1 fw-bold">{{ title }}</h1>
                            <span>¿Ya tienes una cuenta?
								<a href="{% url 'users:login' %}" class="ms-1">Iniciar sesión</a></span>
                        </div>
                        <!-- Form -->
                        <form class="form-s row" autocomplete="off" method="POST" enctype="multipart/form-data"
                              action="{{ request.path }}">
                            {% csrf_token %}
                            {% block action %}
                                <input type="hidden" name="action" value="{{ action }}">
                            {% endblock %}
                            <div class="alert alert-danger d-flex align-items-center d-none" id="text-alerta"
                                 role="alert">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
                                     class="bi bi-exclamation-triangle-fill me-2" viewBox="0 0 16 16">
                                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                                </svg>
                                <div id="message_top">
                                </div>
                            </div>
                            {% for item in form %}
                                <div class="col-12 col-lg-{% if item.field.widget.attrs.col %}{{ item.field.widget.attrs.col }}{% else %}12{% endif %} mb-2">
                                    <label for="courseTitle" class="form-label mb-1">{{ item.label }}:</label>
                                    {% if item.field.widget.attrs.editor %}
                                        <input type="hidden" id="id_{{ item.name }}" name="{{ item.name }}"
                                               value="{{ item.value }}">
                                        <div class="miEditor" id="editor_{{ item.name }}"
                                             style="min-height: 10rem"></div>
                                    {% elif item.field.widget.attrs.switch and item.widget_type == 'checkbox' %}
                                        <span class="form-check form-switch form-switch-price">
                                                        {{ item }}
                                                    </span>
                                    {% else %}
                                        {{ item }}
                                    {% endif %}
                                    <div class="ps-1">
                                        <p class="lh-2"><small>{{ item.help_text }}</small></p>
                                        <small><p class="lh-2 text-danger errorField"
                                                  id="errorField{{ item.name }}"></p></small>
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="mb-3">
                                <div class="form-check">
                                    <input type="checkbox" class="form-check-input" id="agreeCheck" required/>
                                    <label class="form-check-label" for="agreeCheck">
                                        <span>Acepto los <a href="terms-condition-page.html"> Términos de servicio </a>
                                            y <a href="terms-condition-page.html">La política de privacidad.</a></span></label>
                                </div>
                            </div>
                            <div>
                                <!-- Button -->
                                <div class="d-grid">
                                    <button type="submit" class="btn btn-primary">
                                        Crear cuenta gratis
                                    </button>
                                </div>
                            </div>
                            <hr class="my-4"/>
                            <div class="mt-4 text-center">
                                <!--Facebook-->
                                <a href="#" class="btn-social btn-social-outline btn-facebook">
                                    <i class="mdi mdi-facebook fs-4"></i>
                                </a>
                                <!--Twitter-->
                                <a href="#" class="btn-social btn-social-outline btn-twitter">
                                    <i class="mdi mdi-twitter fs-4"></i>
                                </a>
                                <!--LinkedIn-->
                                <a href="#" class="btn-social btn-social-outline btn-linkedin">
                                    <i class="mdi mdi-linkedin"></i>
                                </a>
                                <!--GitHub-->
                                <a href="#" class="btn-social btn-social-outline btn-github">
                                    <i class="mdi mdi-github"></i>
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content_js %}
    <script type="text/javascript" src="{% static 'js/formquestion.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/validators.js' %}"></script>
{% endblock %}

users/templates/control_acceso/validate_token.html
{% extends 'base.html' %}
{% load static %}
{% block content_js %}
    <script type="text/javascript" src="{% static 'js/formquestion.js' %}"></script>
{% endblock %}
  <!-- Page content -->
{% block content %}
    <div class="container d-flex flex-column">
        <div class="row align-items-center justify-content-center g-0 min-vh-100">

          <div class="col-lg-5 col-md-8 py-8 py-xl-0">
            <!-- Card -->
            <div class="card shadow ">
              <!-- Card body -->
              <div class="card-body p-6">
                <div class="mb-4">
                  <a href="../index.html"><img src="../assets/images/brand/logo/logo-icon.svg" class="mb-4" alt=""></a>
                  <h1 class="mb-1 fw-bold">Validar acceso</h1>
                  <span>Se te envio un código de acceso a <a href="">{{persona.email}}</a> para poder ingresar</span>
                </div>
                <!-- Form -->
                <form  class="sign-in-form form-s" autocomplete="off" method="POST" enctype="multipart/form-data" action="{{ request.path }}">
                    {% csrf_token %}
                      <div class="mb-3">
                        <label for="token" class="form-label">Código de verificación <b class="text-danger">*</b>:</label>
                        <input type="text" id="token" class="form-control" name="token" placeholder="Ingrese su código de verificación" required>
                        <span class="text-danger errorField" id="errorFieldcode"></span>
                      </div>
                  <div>
                        <!-- Button -->
                    <div class="row">
                      <div class="col-6">
                        <button type="submit" class="btn btn-primary w-100"><i class="fe fe-check-circle"></i> Validar código</button>
                        
                      </div>
                      <div class="col-6">
                        <a class="btn btn-secondary w-100" href="{% url 'users:logout' %}">
                          <i class="fe fe-power me-2"></i> Salir
                      </a>
                      </div>
                    </div>  
                  </div>
                  <hr class="my-4">
                 
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}