clasificacion_futbol/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path

urlpatterns = [path('admin/', admin.site.urls),
               # CONTROL DE ACCESO USUARIO
               re_path(r'^', include(('users.urls', 'users'), namespace='users')),
               re_path(r'^', include(('clubes.urls', 'clubes'), namespace='clubes')),
               re_path(r'^', include(('core.urls', 'core'), namespace='core')),
               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# Users Urls

# Django
from django.urls import path, re_path

# importaciones de apps
from core import api

urlpatterns = [
    # CONTROL USUARIOS
    re_path(r'^api', api.ViewSet.as_view(), name='api'),
]

users/urls.py
# Users Urls

# Django
from django.urls import path, re_path

# importaciones de apps
from users import control_acceso, adm_panel, adm_users

urlpatterns = [
    # PANTALLAS PRINCIPALES
    re_path(r'^$',adm_panel.HomeView.as_view(), name='home'),
    re_path(r'^main$', adm_panel.MainView.as_view(), name='main'),

    # ACCESO AL SISTEMA
    re_path(r'^login$',control_acceso.LoginView.as_view(), name='login'),
    re_path(r'^signup$',control_acceso.SignupView.as_view(), name='signup'),
    re_path(r'^logout$',control_acceso.LogoutView.as_view(), name='logout'),
    re_path(r'^validate_token$', control_acceso.validate_token, name='validate_token'),

    # CONTROL USUARIOS
    re_path(r'^usuarios$', adm_users.ViewSet.as_view(), name='usuarios'),

    # re_path(r'^administrativos$', administrativos.ViewSet.as_view(), name='administrativos'),
    # # re_path(r'^estudiantes$', estudiantes.ViewSet.as_view(), name='estudiantes'),
    # re_path(r'^docentes$', docentes.ViewSet.as_view(), name='docentes'),
]

users/models/models_profile.py
import datetime
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q

from django.contrib.auth.models import User
from users.models.models_address import Pais, Provincia, Ciudad
from core.funciones import ruta_foto
from core.models import ModeloBase
from django.forms import model_to_dict

SEXO = (
    (1, u'Hombre'),
    (2, u'Mujer'),
)

PERFIL_USUARIO = (
    (0, 'Sin perfil'),
    (1, 'Administrador'),
    (2, 'Secretario'),
    (3, 'Asistente'),
    (4, 'Cliente'),
)

class Persona(ModeloBase):
    usuario = models.ForeignKey(User, null=True, blank=True,  on_delete=models.CASCADE)
    perfil = models.IntegerField(choices=PERFIL_USUARIO, default=0, verbose_name=u'Tipo de usuario')
    nombres = models.CharField(default='', max_length=100, verbose_name=u'Nombre')
    apellido1 = models.CharField(default='', max_length=50, verbose_name=u"1er Apellido")
    apellido2 = models.CharField(default='', max_length=50, verbose_name=u"2do Apellido")
    cedula = models.CharField(default='', max_length=20, verbose_name=u"Cedula", blank=True, db_index=True)
    pasaporte = models.CharField(default='', max_length=20, blank=True, verbose_name=u"Pasaporte", db_index=True)
    fecha_nacimiento = models.DateField(verbose_name=u"Fecha de nacimiento o constitución", blank=True, null=True,)
    sexo = models.IntegerField(choices=SEXO, verbose_name=u'Sexo', blank=True, null=True)
    celular = models.CharField(default='', max_length=50, verbose_name=u"Telefono movil")
    telefono = models.CharField(default='', max_length=50, verbose_name=u"Telefono fijo")
    email = models.CharField(default='', max_length=200, verbose_name=u"Correo electrónico personal")
    nacionalidad = models.ForeignKey(Pais,blank=True, null=True,related_name='nacionalidades', on_delete=models.CASCADE, verbose_name="Nacionalidad que tiene el usuario")
    pais = models.ForeignKey(Pais, blank=True, null=True, related_name='+', verbose_name=u'País residencia', on_delete=models.CASCADE)
    provincia = models.ForeignKey(Provincia, blank=True, null=True, related_name='+',verbose_name=u"Provincia de residencia", on_delete=models.CASCADE)
    ciudad = models.ForeignKey(Ciudad, blank=True, null=True, related_name='+', verbose_name=u"Ciudad de residencia", on_delete=models.CASCADE)
    direccion = models.CharField(default='', max_length=300, verbose_name=u"Calle principal")
    foto = models.ImageField(upload_to='users/foto', verbose_name=u'Foto',blank=True, null=True)
    dosfactores = models.BooleanField(default=False, verbose_name='Autenticacion de dos factores')
    codigoacceso = models.CharField(default='', max_length=50, verbose_name=u"Codigo de acceso")
    autenticado = models.BooleanField(default=False, verbose_name='Verificación de acceso')

    def __str__(self):
        return self.nombres_completos_inverso()

    def nombres_completos_inverso(self):
        nombre_completo = f"{self.apellido1} {self.apellido2} {self.nombres}"
        return nombre_completo.title()

    def nombres_completos_lienal(self):
        nombre_completo = f"{self.nombres} {self.apellido1} {self.apellido2}"
        return nombre_completo.title()

    def nombres_simple(self):
        nombre_completo = self.nombres.split()[0].title()
        apellido1 = self.apellido1.title()
        return f"{nombre_completo} {apellido1}"

    def get_avatar_html_40px(self):
        if self.foto:
            return f'<div class="avatar avatar-md avatar-indicators avatar-online"><img alt="avatar" src="{self.foto.url}"class="rounded-circle"/></div>'
        else:
            siglas=self.nombres[0].upper()+self.apellido1[0].upper()
            return f'<div class="siglas-md mt-0 ml-1"> <span class="mt-0">{siglas}</span></div>'

    def get_avatar_img_md(self):
        if self.foto:
            return f'<img src="{self.foto.url}" class="rounded-circle avatar-md me-2"/>'
        else:
            siglas=self.nombres[0].upper()+self.apellido1[0].upper()
            return f'<div class="siglas-md mt-0 ml-1 me-2"> <span class="mt-0">{siglas}</span></div>'

    def get_avatar_img_sm(self):
        if self.foto:
            return f'<img src="{self.foto.url}" class="rounded-circle avatar-sm me-2"/>'
        else:
            siglas=self.nombres[0].upper()+self.apellido1[0].upper()
            return f'<div class="siglas-sm mt-0 ml-1 me-2"> <span class="mt-0">{siglas}</span></div>'

    def get_foto(self):
        return self.foto.url if self.foto else ''

    def to_dict(self):
        persona_dict=model_to_dict(self)
        for key, value in persona_dict.items():
            if isinstance(value, datetime.date):
                persona_dict[key] = value.strftime('%Y-%m-%d')
        return persona_dict

    def validate_unique(self, exclude=None):
        super().validate_unique(exclude=exclude)
        qs = Persona.objects.filter((Q(cedula=self.cedula) |
                                    Q(cedula=self.pasaporte) |
                                    Q(pasaporte=self.pasaporte) |
                                    Q(pasaporte=self.cedula) |
                                    Q(usuario__email=self.email) |
                                    Q(email=self.email)), status=True).exclude(pk=self.pk).exclude(pasaporte='',pasaporte__isnull=False).exclude(cedula__isnull=False, cedula='')
        if qs.exists():
            raise NameError('Ya existe un registro con los datos que intenta registrar.')

    class Meta:
        verbose_name = u"Persona"
        verbose_name_plural = u"Personas"
        ordering = ['apellido1', 'apellido2', 'nombres']

class UsuariosAcceso(ModeloBase):
    cedula = models.CharField(default='', max_length=20, verbose_name=u"Cedula", blank=True, db_index=True)
    email = models.CharField(default='', max_length=200, verbose_name=u"Correo electrónico personal")
    
    def __str__(self):
        return self.cedula
    
    class Meta:
        verbose_name = u"Usuario Acceso"
        verbose_name_plural = u"Usuarios Acceso"

   

users/forms.py
from django.contrib.auth import authenticate
from django.contrib.auth.hashers import check_password
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.db.models import Q
from django.core import validators
from django.core.exceptions import ValidationError
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
# models
from django.contrib.auth.models import User

from clubes.models import TIPO_ROL, TIPO_JUGADOR, Club, Torneo
from core.forms import FormBase, FormBaseUser, deshabilitar_campo
from core.funciones import generar_username
from core.validators import SoloLetras, v_cedulaform
from users.models import SEXO, Pais, PERFIL_USUARIO
from users.models.models_profile import UsuariosAcceso


class LoginForm(forms.Form):
    email = forms.CharField(label='Correo electrónico o nombre de usuario', widget=forms.TextInput())
    password = forms.CharField(label='Contraseña', max_length=70, widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].error_messages = {'required': f'Este campo es requerido'}

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = cleaned_data.get('email').lower()
        password = cleaned_data.get('password')
        if not User.objects.filter(Q(email=email) | (Q(username=email))).exists():
            self.add_error('email', 'No existe usuario con los datos ingresado.')
        else:
            usuario = User.objects.get(Q(email=email) | (Q(username=email)))
            cleaned_data['username'] = usuario.username
            if not usuario.is_active:
                self.add_error('email', 'Este usuario ha sido desactivado.')
            elif not check_password(password, usuario.password):
                self.add_error('password', 'Contraseña incorrecta.')
        return self.cleaned_data


class SignupForm(FormBaseUser):
    cedula = forms.CharField(label=u"Cédula", max_length=10, required=False,
                             widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingresa tu numero de cédula', 'class': 'soloNumeros'}))
    nombres = forms.CharField(label=u'Nombres', max_length=100, required=True,
                              widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingra tus nombres completos', 'class': 'soloLetrasET'}))
    apellido1 = forms.CharField(label=u"Primer apellido", max_length=50, required=True,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingresa tu primer apellido', 'class': 'soloLetrasET'}))
    apellido2 = forms.CharField(label=u"Segundo apellido", max_length=50, required=True,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingresa tu segundo apellido', 'class': 'soloLetrasET'}))
    fecha_nacimiento = forms.DateField(label=u'Fecha nacimiento', required=True,
                                       widget=forms.DateTimeInput(attrs={'col': '6'}))
    nacionalidad = forms.ModelChoiceField(label=u'Nacionalidad', required=False,
                                          queryset=Pais.objects.filter(status=True),
                                          widget=forms.Select(attrs={'col': '6'}))
    celular = forms.CharField(label=u"Teléfono celular", max_length=50, required=False,
                              widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingresa tu telefono celular', 'class': 'soloNumeros'}))
    email = forms.CharField(label=u"Correo electrónico", max_length=200, required=True,
                            widget=forms.EmailInput(attrs={'col': '6', 'placeholder': 'Ingresa tu correo electrónico'}))
    password = forms.CharField(label="Contraseña", max_length=70, widget=forms.PasswordInput(attrs={'col': '6', 'placeholder': 'Ingresa tu contraseña'}))
    password_confirmation = forms.CharField(label="Confirmar contraseña", max_length=70, widget=forms.PasswordInput(attrs={'col': '6', 'placeholder': 'Ingresa tu contraseña'}))

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)

    def clean(self):
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']
        if 'cedula' in data and 'email' in data:
            cedula = data['cedula']
            email = data['email']
            ua=UsuariosAcceso.objects.filter(cedula=cedula, email=email, status=True).exists()
            if not ua:
                self.add_error('cedula','Usuario con los datos proporcionado no tienen permiso de registro')
                self.add_error('email','Usuario con los datos proporcionado no tienen permiso de registro')
        if len(password) >= 6:
            if password.islower() or password.isupper():
                msg = "La contraseña tiene que tener por lo menos 1 letra mayuscula y 1 minuscula"
                self.add_error('password', msg)
            if password.isdigit() or password.isalpha():
                msg = "La contraseña tiene que contener números, letras y caracteres especiales"
                self.add_error('password', msg)
        else:
            msg = "La contraseña tiene que tener como minimo 6 dígitos"
            self.add_error('password', msg)

        if password != password_confirmation:
            msg = "Contraseña no coincide"
            self.add_error('password_confirmation', msg)
        return data


class UsuarioForm(FormBaseUser):
    nombres = forms.CharField(label=u'Nombres', max_length=100, required=True,
                              widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese los nombres del administrativo', 'class': 'soloLetrasET'}))
    apellido1 = forms.CharField(label=u"Primer apellido", max_length=50, required=True,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese el primer apellido del administrativo', 'class': 'soloLetrasET'}))
    apellido2 = forms.CharField(label=u"Segundo apellido", max_length=50, required=True,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese el segundo apellido del administrativo', 'class': 'soloLetrasET'}))
    cedula = forms.CharField(label=u"Cédula", max_length=10, required=False,
                             widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese la cédula del administrativo', 'class': 'soloNumeros'}))
    fecha_nacimiento = forms.DateField(label=u'Fecha nacimiento', required=True,
                                       widget=forms.DateTimeInput(attrs={'col': '6'}))
    pasaporte = forms.CharField(label=u"Pasaporte", max_length=13, required=False,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese el pasaporte del administrativo'}))
    celular = forms.CharField(label=u"Teléfono celular", max_length=50, required=True,
                              widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese el teléfono celular del administrativo', 'class': 'soloNumeros'}))
    telefono = forms.CharField(label=u"Teléfono", max_length=50, required=False,
                               widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese el teléfono del administrativo (opcional)', 'class': 'soloNumeros'}))
    email = forms.CharField(label=u"Correo electrónico", max_length=200, required=True,
                            widget=forms.EmailInput(attrs={'col': '6', 'placeholder': 'Ingrese el correo electrónico del administrativo'}))
    sexo = forms.ChoiceField(label=u"Genero", required=True,
                             choices=SEXO,
                             widget=forms.Select(attrs={'col': '6'}))
    nacionalidad = forms.ModelChoiceField(label=u'Nacionalidad', required=False,
                                          queryset=Pais.objects.filter(status=True),
                                          widget=forms.Select(attrs={'col': '6'}))
    perfil = forms.ChoiceField(label=u'Perfil', required=True,
                               choices=PERFIL_USUARIO[1:4],
                               widget=forms.Select(attrs={'col': '6'}))
    direccion = forms.CharField(label=u"Dirección de domicilio", max_length=50, required=False,
                                widget=forms.TextInput(attrs={'col': '6', 'placeholder': 'Ingrese su dirección de calle principal'}))
    foto = forms.ImageField(label="Foto", required=False, widget=forms.FileInput(attrs={'col': '6'}))

    def edit(self):
        deshabilitar_campo(self, 'email')
        if self.instancia:
            cedula = getattr(self.instancia, 'cedula', None)
            pasaporte = getattr(self.instancia, 'pasaporte', None)
            if cedula:
                deshabilitar_campo(self, 'cedula')
            if pasaporte:
                deshabilitar_campo(self, 'pasaporte')

class UsuarioPermisoForm(FormBase):
    cedula = forms.CharField(label=u"Cédula", max_length=10, required=True,
                             widget=forms.TextInput(attrs={'col': '12', 'placeholder': 'Ingrese la cédula del administrativo', 'class': 'soloNumeros'}))
    email = forms.CharField(label=u"Correo electrónico", max_length=200, required=True,
                            widget=forms.EmailInput(attrs={'col': '12', 'placeholder': 'Ingrese el correo electrónico del administrativo'}))

    def clean(self):
       cleaned_data = super().clean()
       cedula=cleaned_data.get('cedula')
       email=cleaned_data.get('email')
       v_cedulaform(self, cedula, 'cedula')
       id = getattr(self.instancia, 'id', 0)

       ua=UsuariosAcceso.objects.filter(Q(cedula=cedula) | Q(email=email),status=True).exclude(id=id).exists()
       if ua:
           self.add_error('email', 'Registro que intenta agregar ya se encuentra creado')

users/templates/usuarios/permisos.html
{% extends 'base_admin.html' %}
{% load static %}
{% load extra_tags %}
{% block heading %}{% endblock %}
{% block extra_js %}
    <script type="text/javascript">
        $(function (){
            $("#l_total").text('({{ listado.count }})')
        })
    </script>
{% endblock %}
{% block url_atras %} {{request.path}}{% endblock %}
{% block enlaces_top %}
    <li class="breadcrumb-item"><a href="{{request.path}}">Usuarios</a></li>
    <li class="breadcrumb-item">{{ title }}</li>
{% endblock %}
{% block botones_top %}
    <div class="nav btn-group" role="tablist">
        <a href="javascript:void(0)"
            onclick="formModal('','Adicionar Permiso', 'addpermiso','modal-md')"
        class="btn btn-success btn-xs btn-xl" title="Adicionar prmiso de registro en la plataforma" data-bs-toggle="tooltip"> <i class="fas fa-plus"></i> Adicionar</a>
    </div>
{% endblock %}
{% block content_1 %}
    <div class="row mb-3">
        <form class="col-12" method="GET">
            <!-- Card header -->
            <div class="card-header border-bottom-0 p-0 bg-white">
                <div class="d-flex align-items-center">
                    <input type="hidden" name="action" value="{{action}}">
                    <span class="position-absolute ps-3 search-icon">
                        <i class="fe fe-search"></i>
                    </span>
                    <input type="search" class="form-control ps-6" name="s" placeholder="Buscar por cédula o correo electronico..." value="{{ s }}"/>
                </div>
            </div>
        </form>
    </div>
    <div class="row">
        <div class="col-12">
        <div class="card">
            <!-- table -->
            <div class="table-responsive">
                <table class="table mb-0 text-nowrap table-bordered" id="l_table">
                    <thead class="table-light">
                        <tr>
                             <th scope="col" class="text-center w-5">
                                <i class="fas fa-sort-numeric-asc"></i>
                            </th>
                            <th scope="col" class="w-15">
                                Cédula
                            </th>
                            <th scope="col" class="">
                                Correo
                            </th>
                            <th scope="col" class="text-center w-5">
                                <i class="fas fa-cogs"></i>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for l in listado %}
                        <tr>
                            <td class="text-center align-middle w-5">{{ forloop.counter }}</td>
                            <td class="align-middle border-top-0 w-20">
                               {{l.cedula}}
                            </td>
                            
                            <td class="align-middle border-top-0 w-15 lh-15">
                                {{l.email}}
                            </td>
                           
                            <td class="align-middle border-top-0 text-center w-5">
                                <span class="dropdown dropstart">
                                  <a class="btn-icon btn btn-sm rounded-circle" href="#"
                                     role="button"
                                     id="courseDropdown1"
                                     data-bs-toggle="dropdown" data-bs-offset="-20,20"
                                     aria-expanded="false">
                                  <i class="fe fe-more-vertical"></i>
                                  </a>
                                  <span class="dropdown-menu" aria-labelledby="courseDropdown1">
                                  <span class="dropdown-header"><i class="fas fa-cogs"></i> Acciones</span>
                                    <a class="dropdown-item"
                                       href="javascript:void(0)"
                                       onclick="formModal('{{l.pk|encrypt}}','Editar Permiso', 'editpermiso','modal-md')">
                                        <i class="fe fe-edit dropdown-item-icon"></i>Editar
                                    </a>
                                    {% if not l.perfil == 1 %}
                                    <a class="dropdown-item" href="javascript:void(0);"
                                         onclick="eliminarajax('{{ l.pk|encrypt }}','{{l}}','delpermiso')">
                                        <i class="fas fa-trash dropdown-item-icon"></i> Eliminar
                                    </a>
                                    {%endif%}
                                  </span>
                                </span>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5" class="text-center">No existen registros</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <!-- Pagination -->
                {% include 'paginador.html' %}
            </div>
        </div>
        </div>
    </div>
{% endblock %}

users/templates/usuarios/view.html
{% extends 'base_admin.html' %}
{% load static %}
{% load extra_tags %}
{% block heading %}{% endblock %}
{% block extra_js %}
    <script type="text/javascript">
        $(function (){
            $("#l_total").text('({{ listado.count }})')
        })
    </script>
{% endblock %}
{% block enlaces_top %}
    <li class="breadcrumb-item">{{ title }}</li>
{% endblock %}
{% block botones_top %}
    <div class="nav btn-group" role="tablist">
        <a href="{% url 'users:usuarios' %}?action=permisos" class="btn btn-primary btn-xs btn-xl" title="Listado de identificaciones con permiso de creación" data-bs-toggle="tooltip"> <i class="fas fa-user-check"></i> Permiso de registro</a>
        <a href="{% url 'users:usuarios' %}?action=addusuario" class="btn btn-success btn-xs btn-xl" title="Adicionar usuario" data-bs-toggle="tooltip"> <i class="fas fa-plus"></i> Adicionar</a>
    </div>
{% endblock %}
{% block content_1 %}
    <div class="row mb-3">
        <form class="col-12" method="GET">
            <!-- Card header -->
            <div class="card-header border-bottom-0 p-0 bg-white">
                <div class="d-flex align-items-center">
                    <span class="position-absolute ps-3 search-icon">
                        <i class="fe fe-search"></i>
                    </span>
                    <input type="search" class="form-control ps-6" name="s" placeholder="Buscar por cédula, username, nombres o apellidos..." value="{{ s }}"/>
                </div>
            </div>
        </form>
    </div>
    <div class="row">
        <div class="col-12">
        <div class="card">
            <!-- table -->
            <div class="table-responsive">
                <table class="table mb-0 text-nowrap table-bordered" id="l_table">
                    <thead class="table-light">
                        <tr>
                             <th scope="col" class="text-center w-5">
                                <i class="fas fa-sort-numeric-asc"></i>
                            </th>
                            <th scope="col" class="w-15">
                                Usuario
                            </th>
                            
                           
                            <th scope="col" class="">
                                Detalle
                            </th>
                            <th scope="col" class="text-center">
                                Perfil
                            </th>
                            <th scope="col" class="text-center w-3">
                                Activo
                            </th>
                            <th scope="col" class="text-center w-5">
                                <i class="fas fa-cogs"></i>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for l in listado %}
                        <tr>
                            <td class="text-center align-middle w-5">{{ forloop.counter }}</td>
                            <td class="align-middle border-top-0 w-20">
                                <div class="d-flex align-items-center">
                                    {{ l.get_avatar_img_md|safe }}
                                    <div class="my-0 lh-15">
                                        <p class="fw-bold"></p><i class="fas fa-user"></i> {{ l.nombres_completos_lienal }}</p>
                                        <p class=""><i class="fas fa-id-card-clip"></i> {{ l.cedula }}</p>
                                        <p class=""><i class="fas fa-envelope"></i> {{ l.email }}</p>
                                        <p class=""><i class="fas fa-calendar-day"></i> {{ l.fecha_nacimiento|default_if_none:'S/F' }}</p>
                                    </h5>
                                </div>
                            </td>
                            
                            <td class="align-middle border-top-0 w-15 lh-15">
                                <p><i class="fa-solid fa-venus-mars"></i> {{ l.get_sexo_display|default_if_none:'S/S' }}</p>
                                <p><i class="fa-solid fa-mobile"></i> {{ l.celular }}</p>
                                <p><i class="fa-brands fa-font-awesome"></i> {{ l.nacionalidad.nacionalidad|title|default_if_none:'S/N' }}</p>
                                <p><i class="fa-solid fa-location-dot"></i> {{ l.ciudad|default_if_none:'S/C' }}</p>
                            </td>
                            <td class="align-middle border-top-0 text-center w-5">
                                <p>{{l.get_perfil_display}}</p>
                            </td>
                            <td class="align-middle border-top-0 text-center w-3">
                                {% if l.usuario.is_active %}
                                    <i class="fe fe-check-circle text-success"></i>
                                {% else %}
                                    <i class="fe fe-close text-danger"></i>
                                {% endif %}
                            </td>
                            <td class="align-middle border-top-0 text-center w-5">
                                <span class="dropdown dropstart">
                                  <a class="btn-icon btn btn-sm rounded-circle" href="#"
                                     role="button"
                                     id="courseDropdown1"
                                     data-bs-toggle="dropdown" data-bs-offset="-20,20"
                                     aria-expanded="false">
                                  <i class="fe fe-more-vertical"></i>
                                  </a>
                                  <span class="dropdown-menu" aria-labelledby="courseDropdown1">
                                  <span class="dropdown-header"><i class="fas fa-cogs"></i> Acciones</span>
                                    <a class="dropdown-item"
                                       href="{{ request.path }}?action=editusuario&id={{ l.pk|encrypt }}">
                                        <i class="fe fe-edit dropdown-item-icon"></i>Editar
                                    </a>
                                    {% if not l.perfil == 1 %}
                                    <a class="dropdown-item" href="javascript:void(0);"
                                         onclick="eliminarajax('{{ l.pk|encrypt }}','{{l}}','delusuario')">
                                        <i class="fas fa-trash dropdown-item-icon"></i> Eliminar
                                    </a>
                                    {%endif%}
                                  </span>
                                </span>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5" class="text-center">No existen registros</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <!-- Pagination -->
                {% include 'paginador.html' %}
            </div>
        </div>
        </div>
    </div>
{% endblock %}